In [341]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [342]:
data = pd.read_csv('Indian_housing_Mumbai_data.csv')

In [343]:
data.describe()

latitude    longitude         price  numBathrooms  numBalconies  \
count  5000.000000  5000.000000  5.000000e+03   4986.000000    733.000000   
mean     19.159138    72.953226  6.239421e+04      2.033895      2.064120   
std       0.435495     0.564369  8.874473e+04      0.800861      1.095187   
min      17.468220    72.719688  2.800000e+03      1.000000      1.000000   
25%      19.070265    72.839161  2.100000e+04      2.000000      1.000000   
50%      19.128770    72.884460  4.000000e+04      2.000000      2.000000   
75%      19.195199    72.995323  7.000000e+04      2.000000      3.000000   
max      30.888254    91.792137  1.200000e+06      7.000000      6.000000   

       priceSqFt  
count        0.0  
mean         NaN  
std          NaN  
min          NaN  
25%          NaN  
50%          NaN  
75%          NaN  
max          NaN

In [344]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   house_type        5000 non-null   object 
 1   house_size        5000 non-null   object 
 2   location          5000 non-null   object 
 3   city              5000 non-null   object 
 4   latitude          5000 non-null   float64
 5   longitude         5000 non-null   float64
 6   price             5000 non-null   int64  
 7   currency          5000 non-null   object 
 8   numBathrooms      4986 non-null   float64
 9   numBalconies      733 non-null    float64
 10  isNegotiable      571 non-null    object 
 11  priceSqFt         0 non-null      float64
 12  verificationDate  5000 non-null   object 
 13  description       4922 non-null   object 
 14  SecurityDeposit   5000 non-null   object 
 15  Status            5000 non-null   object 
dtypes: float64(5), int64(1), object(10)
memory

In [345]:
data.shape

(5000, 16)

In [346]:
data.drop('latitude',inplace=True,axis=1)

In [347]:
data.drop('longitude',inplace=True,axis=1)
data.drop('isNegotiable',inplace=True,axis=1)
data.drop('priceSqFt',inplace=True,axis=1)
data.drop('description',inplace=True,axis=1)
data.drop('currency',inplace=True,axis=1)
data.drop('city',inplace=True,axis=1)

In [348]:
data.describe()

price  numBathrooms  numBalconies
count  5.000000e+03   4986.000000    733.000000
mean   6.239421e+04      2.033895      2.064120
std    8.874473e+04      0.800861      1.095187
min    2.800000e+03      1.000000      1.000000
25%    2.100000e+04      2.000000      1.000000
50%    4.000000e+04      2.000000      2.000000
75%    7.000000e+04      2.000000      3.000000
max    1.200000e+06      7.000000      6.000000

In [349]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   house_type        5000 non-null   object 
 1   house_size        5000 non-null   object 
 2   location          5000 non-null   object 
 3   price             5000 non-null   int64  
 4   numBathrooms      4986 non-null   float64
 5   numBalconies      733 non-null    float64
 6   verificationDate  5000 non-null   object 
 7   SecurityDeposit   5000 non-null   object 
 8   Status            5000 non-null   object 
dtypes: float64(2), int64(1), object(6)
memory usage: 351.7+ KB


In [350]:
data.isnull().sum()

house_type             0
house_size             0
location               0
price                  0
numBathrooms          14
numBalconies        4267
verificationDate       0
SecurityDeposit        0
Status                 0
dtype: int64

In [351]:
data['numBathrooms'].fillna(data['numBathrooms'].mean(), inplace=True)

In [352]:
data['numBathrooms'].unique()

array([2.        , 3.        , 1.        , 4.        , 5.        ,
       6.        , 2.03389491, 7.        ])

In [353]:
data['numBalconies'].unique()

array([nan,  2.,  4.,  1.,  5.,  6.,  3.])

In [354]:
data['numBalconies'].fillna(0, inplace=True)

In [355]:
data['numBalconies'].unique()

array([0., 2., 4., 1., 5., 6., 3.])

In [356]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   house_type        5000 non-null   object 
 1   house_size        5000 non-null   object 
 2   location          5000 non-null   object 
 3   price             5000 non-null   int64  
 4   numBathrooms      5000 non-null   float64
 5   numBalconies      5000 non-null   float64
 6   verificationDate  5000 non-null   object 
 7   SecurityDeposit   5000 non-null   object 
 8   Status            5000 non-null   object 
dtypes: float64(2), int64(1), object(6)
memory usage: 351.7+ KB


In [357]:
data.isnull().sum()

house_type          0
house_size          0
location            0
price               0
numBathrooms        0
numBalconies        0
verificationDate    0
SecurityDeposit     0
Status              0
dtype: int64

In [358]:
data.head(5)

house_type   house_size        location  price  numBathrooms  \
0  2 BHK Apartment   1,180 sq ft            Ulwe  19000           2.0   
1  2 BHK Apartment   1,120 sq ft            Ulwe  12500           2.0   
2  2 BHK Apartment   1,200 sq ft          Panvel  22000           2.0   
3  2 BHK Apartment     750 sq ft  Kandivali West  28500           2.0   
4  3 BHK Apartment   1,400 sq ft         Chembur  50000           3.0   

   numBalconies    verificationDate SecurityDeposit          Status  
0           0.0  Posted 2 years ago      No Deposit       Furnished  
1           0.0  Posted 2 years ago      No Deposit     Unfurnished  
2           0.0  Posted a month ago      No Deposit     Unfurnished  
3           0.0  Posted 3 years ago      No Deposit     Unfurnished  
4           0.0  Posted 3 years ago      No Deposit  Semi-Furnished

# Data is now free from null values
Now we will remove the extra symbols from interger values

In [359]:
data['house_type'].head()

0    2 BHK Apartment 
1    2 BHK Apartment 
2    2 BHK Apartment 
3    2 BHK Apartment 
4    3 BHK Apartment 
Name: house_type, dtype: object

In [360]:
data['house_type'].unique()

array(['2 BHK Apartment ', '3 BHK Apartment ', '1 RK Studio Apartment ',
       '1 BHK Apartment ', '4 BHK Apartment ', '1 BHK Independent Floor ',
       '3 BHK Villa ', '3 BHK Independent House ',
       '4 BHK Independent House ', '4 BHK Villa ', '6 BHK Apartment ',
       '2 BHK Independent House ', '5 BHK Apartment ', '1 BHK Villa ',
       '4 BHK Independent Floor ', '6 BHK Villa ', '5 BHK Villa ',
       '3 BHK Independent Floor ', '2 BHK Independent Floor ',
       '6 BHK penthouse ', '1 BHK Independent House '], dtype=object)

In [361]:
data['house_type'] = data['house_type'].str.replace(' ','')

In [362]:
data['house_size'].head()

0    1,180 sq ft
1    1,120 sq ft
2    1,200 sq ft
3      750 sq ft
4    1,400 sq ft
Name: house_size, dtype: object

In [363]:
data['house_size'].str.split()

0       [1,180, sq, ft]
1       [1,120, sq, ft]
2       [1,200, sq, ft]
3         [750, sq, ft]
4       [1,400, sq, ft]
             ...       
4995      [800, sq, ft]
4996    [1,200, sq, ft]
4997    [1,040, sq, ft]
4998    [1,930, sq, ft]
4999    [1,260, sq, ft]
Name: house_size, Length: 5000, dtype: object

In [364]:
data['house_size'].str.split().str.get(0)

0       1,180
1       1,120
2       1,200
3         750
4       1,400
        ...  
4995      800
4996    1,200
4997    1,040
4998    1,930
4999    1,260
Name: house_size, Length: 5000, dtype: object

In [365]:
data['house_size'] = data['house_size'].str.split().str.get(0).str.replace(',','')
data['house_size'].head(8)

0    1180
1    1120
2    1200
3     750
4    1400
5     450
6     700
7     600
Name: house_size, dtype: object

In [366]:
data['location'].unique()

array(['Ulwe', 'Panvel', 'Kandivali West', 'Chembur', 'Badlapur East',
       'Dombivali', 'Bandra West', 'Andheri East', 'Bhayandar East',
       'Goregaon West', 'Colaba', 'Kalamboli', 'Palghar', 'Nerul',
       'Kandivali East', 'Sion', 'Andheri West', 'Juhu', 'Vasai',
       'Thakurli', 'Powai', 'Jogeshwari East', 'Mira Road East',
       'Thane West', 'Parel', 'Prabhadevi', 'Ghatkopar East',
       'Kalyan West', 'Dadar East', 'vile parle west', 'Bhandup West',
       'Borivali East', 'Mahalaxmi', 'Kanjurmarg', 'Seawoods',
       'Dombivali East', 'Titwala', 'Karanjade', 'Girgaon',
       'Malabar Hill', 'Dadar West', 'Goregaon East', 'Mahim', 'Sanpada',
       'Mulund West', 'Tardeo', 'Malad East', 'Borivali West',
       'Malad West', 'Kharghar', 'Jogeshwari West', 'Kamothe',
       'Bandra East', 'Worli', 'Ville Parle East', 'Mulund East',
       'Vikhroli', 'Ghatkopar West', 'Dombivli (West)', 'Cumballa Hill',
       'Khar', 'Vevoor', 'Kanjurmarg East', 'Lower Parel', 'Marine 



*   type done
*   size done
*   location done



In [367]:
data.head(5)

house_type house_size        location  price  numBathrooms  \
0  2BHKApartment       1180            Ulwe  19000           2.0   
1  2BHKApartment       1120            Ulwe  12500           2.0   
2  2BHKApartment       1200          Panvel  22000           2.0   
3  2BHKApartment        750  Kandivali West  28500           2.0   
4  3BHKApartment       1400         Chembur  50000           3.0   

   numBalconies    verificationDate SecurityDeposit          Status  
0           0.0  Posted 2 years ago      No Deposit       Furnished  
1           0.0  Posted 2 years ago      No Deposit     Unfurnished  
2           0.0  Posted a month ago      No Deposit     Unfurnished  
3           0.0  Posted 3 years ago      No Deposit     Unfurnished  
4           0.0  Posted 3 years ago      No Deposit  Semi-Furnished

Changing type

In [368]:
data['numBathrooms'] = data['numBathrooms'].astype(int)
data['numBalconies'] = data['numBalconies'].astype(int)
data['house_size'] = data['house_size'].astype(int)

In [369]:
data['numBathrooms'].unique()

array([2, 3, 1, 4, 5, 6, 7])

In [370]:
data['numBalconies'].unique()

array([0, 2, 4, 1, 5, 6, 3])

In [371]:
data['verificationDate'].unique()

array(['Posted 2 years ago', 'Posted a month ago', 'Posted 3 years ago',
       'Posted 3 months ago', 'Posted 2 months ago', 'Posted 23 days ago',
       'Posted 18 days ago', 'Posted 11 days ago', 'Posted 4 days ago',
       'Posted a day ago', 'Posted 17 days ago', 'Posted 4 months ago',
       'Posted 12 days ago', 'Posted 8 months ago', 'Posted a year ago',
       'Posted 13 days ago', 'Posted 16 days ago', 'Posted 20 days ago',
       'Posted 19 days ago', 'Posted 22 days ago', 'Posted 9 days ago',
       'Posted 15 days ago', 'Posted 21 days ago', 'Posted 14 days ago',
       'Posted 5 days ago', 'Posted 10 days ago', 'Posted 20 hours ago',
       'Posted 8 days ago', 'Posted 2 days ago', 'Posted 24 days ago',
       'Posted 3 days ago', 'Posted 25 days ago', 'Posted 7 days ago',
       'Posted 6 days ago', 'Posted 17 hours ago', 'Posted 5 months ago',
       'Posted 19 hours ago', 'Posted 16 hours ago',
       'Posted 10 hours ago', 'Posted 4 years ago', 'Posted 21 hours ago',


In [372]:
data['verificationDate'] = data['verificationDate'].str.split().str.slice(1,3).str.join(' ')
data['verificationDate']

0       2 years
1       2 years
2       a month
3       3 years
4       3 years
         ...   
4995     a year
4996     a year
4997     a year
4998     a year
4999     a year
Name: verificationDate, Length: 5000, dtype: object

In [373]:
data.head(5)

house_type  house_size        location  price  numBathrooms  \
0  2BHKApartment        1180            Ulwe  19000             2   
1  2BHKApartment        1120            Ulwe  12500             2   
2  2BHKApartment        1200          Panvel  22000             2   
3  2BHKApartment         750  Kandivali West  28500             2   
4  3BHKApartment        1400         Chembur  50000             3   

   numBalconies verificationDate SecurityDeposit          Status  
0             0          2 years      No Deposit       Furnished  
1             0          2 years      No Deposit     Unfurnished  
2             0          a month      No Deposit     Unfurnished  
3             0          3 years      No Deposit     Unfurnished  
4             0          3 years      No Deposit  Semi-Furnished



*   type done
*   size done
*   location done
*   price done
*   bath done
*   bal done
*   veri done









In [374]:
data['SecurityDeposit'].unique()

array(['No Deposit', ' 2,50,000', ' 60,000', ' 1,00,000', ' 2,00,000',
       ' 4,00,000', ' 3,00,000', ' 1,50,000', ' 1,25,000', ' 85,000',
       ' 6,00,000', ' 75,000', ' 50,000', ' 25,000', ' 1,80,000',
       ' 95,000', ' 5,00,000', ' 30,000', ' 90,000', ' 10,000',
       ' 60,00,000', ' 50,00,000', ' 36,00,000', ' 42,00,000',
       ' 18,00,000', ' 1,60,000', ' 45,000', ' 40,000', ' 35,000',
       ' 80,000', ' 2,500', ' 20,000', ' 1,10,000', ' 21,00,000',
       ' 8,00,000', ' 70,000', ' 65,000', ' 4,50,000', ' 10,00,000',
       ' 2,75,000', ' 9,00,000', ' 12,000', ' 1,45,000', ' 7,50,000',
       ' 15,000', ' 3,50,000', ' 12,00,000', ' 7,00,000', ' 5,50,000',
       ' 20,00,000', ' 15,00,000', ' 11,00,000', ' 1,40,000', ' 1,20,000',
       ' 1,65,000', ' 1,35,000', ' 55,000', ' 1,75,000', ' 3,500',
       ' 13,000', ' 30,800', ' 30,200', ' 30,500', ' 30,600', ' 30,400',
       ' 5,40,000', ' 7,000', ' 1,12,000', ' 2,20,000', ' 48,000',
       ' 1,30,000', ' 21,000', ' 2,25,000

In [375]:
data['SecurityDeposit'] = data['SecurityDeposit'].str.replace('No Deposit', '0')

In [376]:
data['SecurityDeposit'] = data['SecurityDeposit'].str.replace(',','')

In [377]:
data['SecurityDeposit'] = data['SecurityDeposit'].astype(int)

In [378]:
data['SecurityDeposit'].unique()

array([      0,  250000,   60000,  100000,  200000,  400000,  300000,
        150000,  125000,   85000,  600000,   75000,   50000,   25000,
        180000,   95000,  500000,   30000,   90000,   10000, 6000000,
       5000000, 3600000, 4200000, 1800000,  160000,   45000,   40000,
         35000,   80000,    2500,   20000,  110000, 2100000,  800000,
         70000,   65000,  450000, 1000000,  275000,  900000,   12000,
        145000,  750000,   15000,  350000, 1200000,  700000,  550000,
       2000000, 1500000, 1100000,  140000,  120000,  165000,  135000,
         55000,  175000,    3500,   13000,   30800,   30200,   30500,
         30600,   30400,  540000,    7000,  112000,  220000,   48000,
        130000,   21000,  225000,  100080,   22000,  240000])

In [379]:
data['Status'].unique()

array(['Furnished', 'Unfurnished', 'Semi-Furnished'], dtype=object)

# Data is Now cleaned and ready for modeling

In [380]:
data.to_csv('cleaned_data.csv')

In [381]:
data

house_type  house_size        location  price  numBathrooms  \
0     2BHKApartment        1180            Ulwe  19000             2   
1     2BHKApartment        1120            Ulwe  12500             2   
2     2BHKApartment        1200          Panvel  22000             2   
3     2BHKApartment         750  Kandivali West  28500             2   
4     3BHKApartment        1400         Chembur  50000             3   
...             ...         ...             ...    ...           ...   
4995  2BHKApartment         800       Saki Naka  46000             2   
4996  2BHKApartment        1200      Malad West  55000             2   
4997  2BHKApartment        1040   Goregaon West  44000             2   
4998  3BHKApartment        1930        Kharghar  65000             3   
4999  2BHKApartment        1260        Kharghar  31500             2   

      numBalconies verificationDate  SecurityDeposit          Status  
0                0          2 years                0       Furnished  
1                0          2 years                0     Unfurnished  
2                0          a month                0     Unfurnished  
3                0          3 years                0     Unfurnished  
4                0          3 years                0  Semi-Furnished  
...            ...              ...              ...             ...  
4995             0           a year           150000     Unfurnished  
4996             0           a year           250000  Semi-Furnished  
4997             0           a year           200000     Unfurnished  
4998             0           a year           200000       Furnished  
4999             1           a year            80000  Semi-Furnished  

[5000 rows x 9 columns]

# Modeling

In [382]:
x = data.drop(columns = 'price')
y = data['price']

In [383]:
x.head(5)

house_type  house_size        location  numBathrooms  numBalconies  \
0  2BHKApartment        1180            Ulwe             2             0   
1  2BHKApartment        1120            Ulwe             2             0   
2  2BHKApartment        1200          Panvel             2             0   
3  2BHKApartment         750  Kandivali West             2             0   
4  3BHKApartment        1400         Chembur             3             0   

  verificationDate  SecurityDeposit          Status  
0          2 years                0       Furnished  
1          2 years                0     Unfurnished  
2          a month                0     Unfurnished  
3          3 years                0     Unfurnished  
4          3 years                0  Semi-Furnished

In [384]:
y.head(5)

0    19000
1    12500
2    22000
3    28500
4    50000
Name: price, dtype: int64

In [385]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.2)

In [386]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [387]:
hot = OneHotEncoder()
hot.fit(x[['house_type','location','verificationDate', 'Status']])

OneHotEncoder()

In [388]:
hot.categories_

[array(['1BHKApartment', '1BHKIndependentFloor', '1BHKIndependentHouse',
        '1BHKVilla', '1RKStudioApartment', '2BHKApartment',
        '2BHKIndependentFloor', '2BHKIndependentHouse', '3BHKApartment',
        '3BHKIndependentFloor', '3BHKIndependentHouse', '3BHKVilla',
        '4BHKApartment', '4BHKIndependentFloor', '4BHKIndependentHouse',
        '4BHKVilla', '5BHKApartment', '5BHKVilla', '6BHKApartment',
        '6BHKVilla', '6BHKpenthouse'], dtype=object),
 array(['Aarya Chanakya Nagar', 'Agripada', 'Airoli', 'Akurli Road',
        'Akurli Road Number 1', 'Ambernath East', 'Ambernath West',
        'Amrut Nagar', 'Andheri East', 'Andheri West', 'Antarli', 'Babhai',
        'Babhai Naka', 'Badlapur East', 'Badlapur West', 'Balkum',
        'Bandra East', 'Bandra Kurla Complex', 'Bandra West', 'Belapur',
        'Bhandup East', 'Bhandup West', 'Bhayandar East', 'Bhayandar West',
        'Bhiwandi', 'Boisar', 'Borivali (West)', 'Borivali East',
        'Borivali West', 'Breach Ca

In [389]:
column_trans = make_column_transformer((OneHotEncoder(categories = hot.categories_), ['house_type','location','verificationDate', 'Status']), remainder='passthrough')
# handle_unknown='ignore' you can use

In [390]:
column_trans

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder',
                                 OneHotEncoder(categories=[array(['1BHKApartment', '1BHKIndependentFloor', '1BHKIndependentHouse',
       '1BHKVilla', '1RKStudioApartment', '2BHKApartment',
       '2BHKIndependentFloor', '2BHKIndependentHouse', '3BHKApartment',
       '3BHKIndependentFloor', '3BHKIndependentHouse', '3BHKVilla',
       '4BHKApartmen...
       '20 days', '20 hours', '21 days', '21 hours', '22 days', '23 days',
       '24 days', '25 days', '3 days', '3 months', '3 years',
       '33 minutes', '4 days', '4 months', '4 years', '5 days',
       '5 months', '5 years', '6 days', '6 months', '7 days', '8 days',
       '8 months', '9 days', '9 months', 'a day', 'a month', 'a year',
       'an hour'], dtype=object),
                                                           array(['Furnished', 'Semi-Furnished', 'Unfurnished'], dtype=object)]),
                                 ['house_type', 'location', 'verificationDate',
                                  'Status'])])

In [391]:
lr = LinearRegression()

In [392]:
pipe = make_pipeline(column_trans, lr)

In [393]:
pipe.fit(xtrain,ytrain)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['1BHKApartment', '1BHKIndependentFloor', '1BHKIndependentHouse',
       '1BHKVilla', '1RKStudioApartment', '2BHKApartment',
       '2BHKIndependentFloor', '2BHKIndependentHouse', '3BHKApartment',
       '3BHKIndependentFloor', '3BHKIndepe...
       '24 days', '25 days', '3 days', '3 months', '3 years',
       '33 minutes', '4 days', '4 months', '4 years', '5 days',
       '5 months', '5 years', '6 days', '6 months', '7 days', '8 days',
       '8 months', '9 days', '9 months', 'a day', 'a month', 'a year',
       'an hour'], dtype=object),
                                                                            array(['Furnished', 'Semi-Furnished', 'Unfurnished'], dtype=object)]),
                                                  ['house_type', 'location',
                                                   'verificationDate',
                                                   'Status'])])),
                ('linearregression', LinearRegression())])

In [394]:
y_pred = pipe.predict(xtest)

In [395]:
y_pred

array([ 7.26287686e+04,  2.86054553e+04,  6.26234726e+04,  1.60987610e+04,
        4.06118771e+04,  2.86054553e+04,  1.17652899e+05,  4.76155586e+04,
        7.26288186e+04,  2.46033719e+04,  1.10960783e+04,  2.56038071e+04,
        3.76103171e+04,  5.84212844e+04,  1.25969100e+04,  5.41189783e+04,
        3.76102993e+04,  4.06118635e+04,  4.06118771e+04,  6.26235350e+04,
        5.76208507e+04,  2.11365886e+05,  5.66474422e+04, -1.87561199e+04,
        4.76155393e+04, -1.24163150e+04,  5.76208992e+04,  1.59986699e+04,
        2.61358121e+04,  2.01326038e+04,  1.12650280e+05,  4.81158334e+04,
        1.81672652e+05,  2.26022007e+04,  6.76261535e+04,  2.06012449e+04,
        1.27969864e+04,  6.26235244e+04,  4.21101030e+04,  3.76101318e+04,
        9.76421020e+04,  4.26129356e+04,  3.21049086e+04,  1.15965144e+04,
        1.60988948e+04,  6.76261915e+04,  1.03645247e+05, -8.75082371e+03,
        1.75996576e+04,  7.62941935e+04,  1.05913221e+04,  9.41402172e+04,
        1.00643787e+05,  

In [396]:
r2_score(ytest, y_pred)

0.6096167381273958

In [397]:
mean_absolute_error(ytest, y_pred)

34705.75736799734

In [398]:
mean_squared_error(ytest, y_pred)

3880828268.639419

In [399]:
for i in range(10):
  xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.2)
  lr = LinearRegression()
  pipe = make_pipeline(column_trans, lr)
  pipe.fit(xtrain, ytrain)
  y_pred = pipe.predict(xtest)
  print(r2_score(ytest, y_pred))

0.6648564159145676
0.688637905935342
0.501326223267094
0.5275703195322634
0.6511364552690582
0.5593911889377868
0.5474397331597098
0.5822687152373065
0.5211669507093548
0.4945931149776396


In [400]:
score = []

for i in range(1000):
  xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.2, random_state=i)
  lr = LinearRegression()
  pipe = make_pipeline(column_trans, lr)
  pipe.fit(xtrain, ytrain)
  y_pred = pipe.predict(xtest)
  score.append(r2_score(ytest, y_pred))

In [401]:
np.argmax(score)

121

In [402]:
score[np.argmax(score)]

0.7624397705591778

In [403]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.2, random_state=np.argmax(score))
lr = LinearRegression()
pipe = make_pipeline(column_trans, lr)
pipe.fit(xtrain, ytrain)
y_pred = pipe.predict(xtest)
print('R2 Score:',r2_score(ytest, y_pred))
print('Mean absolute error:',mean_absolute_error(ytest, y_pred))
print('Mean squared error:',mean_squared_error(ytest, y_pred))

R2 Score: 0.7624397705591778
Mean absolute error: 29225.40577812229
Mean squared error: 2012471391.300895


In [404]:
data.head(5)

house_type  house_size        location  price  numBathrooms  \
0  2BHKApartment        1180            Ulwe  19000             2   
1  2BHKApartment        1120            Ulwe  12500             2   
2  2BHKApartment        1200          Panvel  22000             2   
3  2BHKApartment         750  Kandivali West  28500             2   
4  3BHKApartment        1400         Chembur  50000             3   

   numBalconies verificationDate  SecurityDeposit          Status  
0             0          2 years                0       Furnished  
1             0          2 years                0     Unfurnished  
2             0          a month                0     Unfurnished  
3             0          3 years                0     Unfurnished  
4             0          3 years                0  Semi-Furnished

In [407]:
pipe.predict(pd.DataFrame([['1BHKApartment', 1180, 'Ulwe', 2, 0, '2 years', 0, 'Furnished']], columns=['house_type','house_size','location','numBathrooms','numBalconies','verificationDate','SecurityDeposit',	'Status']))

array([95226.27920819])

In [408]:
import pickle

In [411]:
pickle.dump(pipe, open('Model.py', 'wb'))